#!/bin/bash

python3 greatestTwoMasses_RMW_numSecondaryCycles_percolatingCluster.py -d /home/mattia/Documents/scriptDeveloper/anlammps/lammps/lammpsData/data.Min_large3 -c /home/mattia/Documents/emmy_backup/large_503K_1/dump/dump.1_btype_batom1_batom2_nptCuring_gelation -t /home/mattia/Documents/emmy_backup/large_503K_1/dump/dump.1_atomId_type_scaledCoords_nptCuring_gelation -o /home/mattia/Documents/epoxy/crossLinkingAndGelationPoint/systems/large1/gelPoint/gelPointMeasurements1_2nsNptCuring

python3 greatestTwoMasses_RMW_numSecondaryCycles_percolatingCluster.py -d /home/mattia/Documents/scriptDeveloper/anlammps/lammps/lammpsData/data.Min_large3 -c /home/mattia/Documents/emmy_backup/large_503K_2/dump/dump.1_btype_batom1_batom2_nptCuring_gelation -t /home/mattia/Documents/emmy_backup/large_503K_2/dump/dump.1_atomId_type_scaledCoords_nptCuring_gelation -o /home/mattia/Documents/epoxy/crossLinkingAndGelationPoint/systems/large2/gelPoint/gelPointMeasurements1_2nsNptCuring

python3 greatestTwoMasses_RMW_numSecondaryCycles_percolatingCluster.py -d /home/mattia/Documents/scriptDeveloper/anlammps/lammps/lammpsData/data.Min_large3 -c /home/mattia/Documents/emmy_backup/large_503K_3/dump/dump.1_btype_batom1_batom2_nptCuring_gelation -t /home/mattia/Documents/emmy_backup/large_503K_3/dump/dump.1_atomId_type_scaledCoords_nptCuring_gelation -o /home/mattia/Documents/epoxy/crossLinkingAndGelationPoint/systems/large3/gelPoint/gelPointMeasurements1_2nsNptCuring

python3 greatestTwoMasses_RMW_numSecondaryCycles_percolatingCluster.py -d /home/mattia/Documents/scriptDeveloper/anlammps/lammps/lammpsData/data.Min_large3 -c /home/mattia/Documents/emmy_backup/large_503K_4/dump/dump.1_btype_batom1_batom2_nptCuring_gelation -t /home/mattia/Documents/emmy_backup/large_503K_4/dump/dump.1_atomId_type_scaledCoords_nptCuring_gelation -o /home/mattia/Documents/epoxy/crossLinkingAndGelationPoint/systems/large4/gelPoint/gelPointMeasurements1_2nsNptCuring

python3 greatestTwoMasses_RMW_numSecondaryCycles_percolatingCluster.py -d /home/mattia/Documents/scriptDeveloper/anlammps/lammps/lammpsData/data.Min_large3 -c /home/mattia/Documents/emmy_backup/large_503K_5/dump/dump.1_btype_batom1_batom2_nptCuring_gelation -t /home/mattia/Documents/emmy_backup/large_503K_5/dump/dump.1_atomId_type_scaledCoords_nptCuring_gelation -o /home/mattia/Documents/epoxy/crossLinkingAndGelationPoint/systems/large5/gelPoint/gelPointMeasurements1_2nsNptCuring

python3 greatestTwoMasses_RMW_numSecondaryCycles_percolatingCluster.py -d /home/mattia/Documents/scriptDeveloper/anlammps/lammps/lammpsData/data.Min_medium1 -c /home/mattia/Documents/emmy_backup/medium_503K_1/dump/dump.1_btype_batom1_batom2_nptCuring_gelation -t /home/mattia/Documents/emmy_backup/medium_503K_1/dump/dump.1_atomId_type_scaledCoords_nptCuring_gelation -o /home/mattia/Documents/epoxy/crossLinkingAndGelationPoint/systems/medium1/gelPoint/gelPointMeasurements1_2nsNptCuring

python3 greatestTwoMasses_RMW_numSecondaryCycles_percolatingCluster.py -d /home/mattia/Documents/scriptDeveloper/anlammps/lammps/lammpsData/data.Min_small1 -c /home/mattia/Documents/emmy_backup/small_503K_1/dump/dump.1_btype_batom1_batom2_nptCuring_gelation -t /home/mattia/Documents/emmy_backup/small_503K_1/dump/dump.1_atomId_type_scaledCoords_nptCuring_gelation -o /home/mattia/Documents/epoxy/crossLinkingAndGelationPoint/systems/small1/gelPoint/gelPointMeasurements1_2nsNptCuring
